var annotated =
[
    [ "ctrlproto_slv_handle", "d2/d80/structctrlproto__slv__handle.html", "d2/d80/structctrlproto__slv__handle" ],
    [ "gear_ratio_s", "d8/dfb/structgear__ratio__s.html", "d8/dfb/structgear__ratio__s" ],
    [ "master_setup_variables_t", "d4/dba/structmaster__setup__variables__t.html", "d4/dba/structmaster__setup__variables__t" ],
    [ "max_acceleration_s", "de/dd0/structmax__acceleration__s.html", "de/dd0/structmax__acceleration__s" ],
    [ "max_profile_velocity_s", "d8/d9c/structmax__profile__velocity__s.html", "d8/d9c/structmax__profile__velocity__s" ],
    [ "max_torque_s", "db/d86/structmax__torque__s.html", "db/d86/structmax__torque__s" ],
    [ "motor_config", "d4/d28/structmotor__config.html", "d4/d28/structmotor__config" ],
    [ "motor_torque_constant_s", "d1/d31/structmotor__torque__constant__s.html", "d1/d31/structmotor__torque__constant__s" ],
    [ "nominal_current_s", "dd/db9/structnominal__current__s.html", "dd/db9/structnominal__current__s" ],
    [ "nominal_motor_speed_s", "df/daa/structnominal__motor__speed__s.html", "df/daa/structnominal__motor__speed__s" ],
    [ "polarity_s", "d7/dc3/structpolarity__s.html", "d7/dc3/structpolarity__s" ],
    [ "pole_pair_s", "d3/dcd/structpole__pair__s.html", "d3/dcd/structpole__pair__s" ],
    [ "pos_quick_stop_param", "db/d33/structpos__quick__stop__param.html", "db/d33/structpos__quick__stop__param" ],
    [ "position_encoder_resolution_s", "dc/da7/structposition__encoder__resolution__s.html", "dc/da7/structposition__encoder__resolution__s" ],
    [ "profile_acceleration_s", "d2/d2d/structprofile__acceleration__s.html", "d2/d2d/structprofile__acceleration__s" ],
    [ "profile_deceleration_s", "d7/d78/structprofile__deceleration__s.html", "d7/d78/structprofile__deceleration__s" ],
    [ "PROFILE_LINEAR_PARAM", "d8/d0a/structPROFILE__LINEAR__PARAM.html", "d8/d0a/structPROFILE__LINEAR__PARAM" ],
    [ "profile_pos_param", "d1/d30/structprofile__pos__param.html", "d1/d30/structprofile__pos__param" ],
    [ "profile_velocity_s", "d2/d6a/structprofile__velocity__s.html", "d2/d6a/structprofile__velocity__s" ],
    [ "qei_commutation_offset_cclk_s", "d5/d58/structqei__commutation__offset__cclk__s.html", "d5/d58/structqei__commutation__offset__cclk__s" ],
    [ "qei_commutation_offset_clk_s", "d7/d43/structqei__commutation__offset__clk__s.html", "d7/d43/structqei__commutation__offset__clk__s" ],
    [ "qei_offset_cclk_s", "df/d38/structqei__offset__cclk__s.html", "df/d38/structqei__offset__cclk__s" ],
    [ "qei_offset_clk_s", "d3/dfa/structqei__offset__clk__s.html", "d3/dfa/structqei__offset__clk__s" ],
    [ "quick_stop_deceleration_s", "d4/d56/structquick__stop__deceleration__s.html", "d4/d56/structquick__stop__deceleration__s" ],
    [ "sensor_selection_code_s", "da/df6/structsensor__selection__code__s.html", "da/df6/structsensor__selection__code__s" ],
    [ "software_position_max_s", "dd/d40/structsoftware__position__max__s.html", "dd/d40/structsoftware__position__max__s" ],
    [ "software_position_min_s", "db/dfb/structsoftware__position__min__s.html", "db/dfb/structsoftware__position__min__s" ],
    [ "torque_slope_s", "d5/d0c/structtorque__slope__s.html", "d5/d0c/structtorque__slope__s" ],
    [ "velocity_d_gain_s", "da/dc1/structvelocity__d__gain__s.html", "da/dc1/structvelocity__d__gain__s" ],
    [ "velocity_i_gain_s", "de/d68/structvelocity__i__gain__s.html", "de/d68/structvelocity__i__gain__s" ],
    [ "velocity_p_gain_s", "d5/db2/structvelocity__p__gain__s.html", "d5/db2/structvelocity__p__gain__s" ]
];