ROS_ecat_master: src/main.cpp File Reference
main.cpp File Reference
Example Master App for Profile Position (on PC)
#include <ctrlproto_m.h>
#include "ethercat_setup.h"
#include "profile.h"
#include "drive_function.h"
#include <motor_define.h>
#include <ecrt.h>
#include <stdio.h>
#include <stdbool.h>
#include <sys/time.h>
#include <time.h>
#include <ros/ros.h>
#include "boost/thread.hpp"
#include "ros_ecat_master/MoveJoint.h"
Macros
#define NODE_1 0
#define NODE_2 1
#define NODE_3 2
#define NODE_4 3
Functions
void cb_move_joints (const ros_ecat_master::MoveJointConstPtr &move)
void ecat_master ()
int main (int argc, char **argv)
Variables
boost::mutex mutex_ethercat_update
double move_degree_j1 = 0.0
double move_degree_j2 = 0.0
double move_degree_j3 = 0.0
double move_degree_j4 = 0.0
double move_speed_j1 = 0.0
double move_speed_j2 = 0.0
double move_speed_j3 = 0.0
double move_speed_j4 = 0.0
double move_degree_j1_old = 0.0
double move_degree_j2_old = 0.0
double move_degree_j3_old = 0.0
double move_degree_j4_old = 0.0
double move_speed_j1_old = 0.0
double move_speed_j2_old = 0.0
double move_speed_j3_old = 0.0
double move_speed_j4_old = 0.0
int cmd = 3
float temp
Detailed Description
Example Master App for Profile Position (on PC)
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com & Christian Holl choll.nosp@m.@syn.nosp@m.aptic.nosp@m.on.c.nosp@m.om
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file main.cpp.
Macro Definition Documentation
#define NODE_1 0
Definition at line 62 of file main.cpp.
Referenced by ecat_master().
#define NODE_2 1
Definition at line 63 of file main.cpp.
Referenced by ecat_master().
#define NODE_3 2
Definition at line 64 of file main.cpp.
Referenced by ecat_master().
#define NODE_4 3
Definition at line 65 of file main.cpp.
Referenced by ecat_master().
Function Documentation
void cb_move_joints (const ros_ecat_master::MoveJointConstPtr & move)
Definition at line 76 of file main.cpp.
References move_degree_j1, move_degree_j2, move_degree_j3, move_degree_j4, move_speed_j1, move_speed_j2, move_speed_j3, move_speed_j4, and mutex_ethercat_update.
Referenced by main().
void ecat_master ()
Definition at line 105 of file main.cpp.
References CSP, enable_operation(), GEAR_RATIO_1, GEAR_RATIO_2, GEAR_RATIO_3, GEAR_RATIO_4, get_position_actual_degree(), init_master(), init_node(), init_position_profile_limits(), init_position_profile_params(), MAX_ACCELERATION_1, MAX_ACCELERATION_2, MAX_ACCELERATION_3, MAX_ACCELERATION_4, MAX_NOMINAL_SPEED_1, MAX_NOMINAL_SPEED_2, MAX_NOMINAL_SPEED_3, MAX_NOMINAL_SPEED_4, move_degree_j1, move_degree_j1_old, move_degree_j2, move_degree_j2_old, move_degree_j3, move_degree_j3_old, move_degree_j4, move_degree_j4_old, move_speed_j1, move_speed_j2, move_speed_j3, move_speed_j4, mutex_ethercat_update, NODE_1, NODE_2, NODE_3, NODE_4, pdo_handle_ecat(), position_profile_generate(), quick_stop_position(), renable_ctrl_quick_stop(), set_operation_mode(), set_position_degree(), shutdown_operation(), and TOTAL_NUM_OF_SLAVES.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 273 of file main.cpp.
References cb_move_joints(), and ecat_master().
Variable Documentation
int cmd = 3
Definition at line 73 of file main.cpp.
double move_degree_j1 = 0.0
Definition at line 69 of file main.cpp.
Referenced by cb_move_joints(), and ecat_master().
double move_degree_j1_old = 0.0
Definition at line 71 of file main.cpp.
Referenced by ecat_master().
double move_degree_j2 = 0.0
Definition at line 69 of file main.cpp.
Referenced by cb_move_joints(), and ecat_master().
double move_degree_j2_old = 0.0
Definition at line 71 of file main.cpp.
Referenced by ecat_master().
double move_degree_j3 = 0.0
Definition at line 69 of file main.cpp.
Referenced by cb_move_joints(), and ecat_master().
double move_degree_j3_old = 0.0
Definition at line 71 of file main.cpp.
Referenced by ecat_master().
double move_degree_j4 = 0.0
Definition at line 69 of file main.cpp.
Referenced by cb_move_joints(), and ecat_master().
double move_degree_j4_old = 0.0
Definition at line 71 of file main.cpp.
Referenced by ecat_master().
double move_speed_j1 = 0.0
Definition at line 70 of file main.cpp.
Referenced by cb_move_joints(), and ecat_master().
double move_speed_j1_old = 0.0
Definition at line 72 of file main.cpp.
double move_speed_j2 = 0.0
Definition at line 70 of file main.cpp.
Referenced by cb_move_joints(), and ecat_master().
double move_speed_j2_old = 0.0
Definition at line 72 of file main.cpp.
double move_speed_j3 = 0.0
Definition at line 70 of file main.cpp.
Referenced by cb_move_joints(), and ecat_master().
double move_speed_j3_old = 0.0
Definition at line 72 of file main.cpp.
double move_speed_j4 = 0.0
Definition at line 70 of file main.cpp.
Referenced by cb_move_joints(), and ecat_master().
double move_speed_j4_old = 0.0
Definition at line 72 of file main.cpp.
boost::mutex mutex_ethercat_update
Definition at line 67 of file main.cpp.
Referenced by cb_move_joints(), and ecat_master().
float temp
Definition at line 74 of file main.cpp.