ROS_ecat_master: include/ctrlproto_m.h File Reference
ctrlproto_m.h File Reference
#include <stdbool.h>
#include <ecrt.h>
#include <inttypes.h>
#include <motor_define.h>
#include "bldc_motor_config_1.h"
#include "bldc_motor_config_2.h"
#include "bldc_motor_config_3.h"
#include "bldc_motor_config_4.h"
Data Structures
struct ctrlproto_slv_handle
struct master_setup_variables_t
Macros
#define MOTOR_PARAM_UPDATE 1
#define VELOCITY_CTRL_UPDATE 2
#define CSV_MOTOR_UPDATE 3
#define POSITION_CTRL_UPDATE 4
#define PV_MOTOR_UPDATE 5
#define PP_MOTOR_UPDATE 6
#define CST_MOTOR_UPDATE 7
#define TORQUE_CTRL_UPDATE 8
#define TQ_MOTOR_UPDATE 9
#define QEI_CALIBRATE_UPDATE 10
#define SOMANET_ID 0x000022d2, 0x00000201
#define CAN_OD_CONTROL_WORD 0x6040 /* RX; 16 bit */
#define CAN_OD_STATUS_WORD 0x6041 /* TX; 16 bit */
#define CAN_OD_MODES 0x6060 /* RX; 8 bit */
#define CAN_OD_MODES_DISPLAY 0x6061 /* TX; 8 bit */
#define CAN_OD_TORQUE_TARGET 0x6071 /* RX; 16 bit */
#define CAN_OD_TORQUE_VALUE 0x6077 /* TX; 16 bit */
#define CAN_OD_POSITION_TARGET 0x607A /* RX; 32 bit */
#define CAN_OD_POSITION_VALUE 0x6064 /* TX; 32 bit */
#define CAN_OD_VELOCITY_TARGET 0x60ff /* RX; 32 bit */
#define CAN_OD_VELOCITY_VALUE 0x606C /* TX; 32 bit */
#define SOMANET_C22_CTRLPROTO_CSTRUCT()
#define SOMANET_C22_CTRLPROTO_SLAVE_HANDLES_ENTRY(ALIAS, POSITION, CONFIG_NUMBER)
#define SOMANET_C22_CTRLPROTO_DOMAIN_REGS_ENTRIES(ALIAS, POSITION, ARRAY_POSITION)
#define MASTER_SETUP_INIT()
Functions
void init_master (master_setup_variables_t *master_setup, ctrlproto_slv_handle *slv_handles, unsigned int total_no_of_slaves)
void pdo_handle_ecat (master_setup_variables_t *master_setup, ctrlproto_slv_handle *slv_handles, unsigned int total_no_of_slaves)
void sdo_handle_ecat (master_setup_variables_t *master_setup, ctrlproto_slv_handle *slv_handles, int update_sequence, int slave_number)
Detailed Description
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com, Christian Holl choll.nosp@m.@syn.nosp@m.aptic.nosp@m.on.c.nosp@m.om & Frank Jeschke jesch.nosp@m.ke@f.nosp@m.jes.d.nosp@m.e
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file ctrlproto_m.h.
Macro Definition Documentation
#define CAN_OD_CONTROL_WORD 0x6040 /* RX; 16 bit */
Definition at line 71 of file ctrlproto_m.h.
#define CAN_OD_MODES 0x6060 /* RX; 8 bit */
Definition at line 73 of file ctrlproto_m.h.
#define CAN_OD_MODES_DISPLAY 0x6061 /* TX; 8 bit */
Definition at line 74 of file ctrlproto_m.h.
#define CAN_OD_POSITION_TARGET 0x607A /* RX; 32 bit */
Definition at line 77 of file ctrlproto_m.h.
#define CAN_OD_POSITION_VALUE 0x6064 /* TX; 32 bit */
Definition at line 78 of file ctrlproto_m.h.
#define CAN_OD_STATUS_WORD 0x6041 /* TX; 16 bit */
Definition at line 72 of file ctrlproto_m.h.
#define CAN_OD_TORQUE_TARGET 0x6071 /* RX; 16 bit */
Definition at line 75 of file ctrlproto_m.h.
#define CAN_OD_TORQUE_VALUE 0x6077 /* TX; 16 bit */
Definition at line 76 of file ctrlproto_m.h.
#define CAN_OD_VELOCITY_TARGET 0x60ff /* RX; 32 bit */
Definition at line 79 of file ctrlproto_m.h.
#define CAN_OD_VELOCITY_VALUE 0x606C /* TX; 32 bit */
Definition at line 80 of file ctrlproto_m.h.
#define CST_MOTOR_UPDATE 7
Definition at line 64 of file ctrlproto_m.h.
Referenced by sdo_motor_config_update(), and set_operation_mode().
#define CSV_MOTOR_UPDATE 3
Definition at line 60 of file ctrlproto_m.h.
Referenced by sdo_motor_config_update(), and set_operation_mode().
#define MASTER_SETUP_INIT ()
Value:
master_setup_variables_t master_setup={\
                false,false,NULL,{},0,{},domain_regs,NULL,\
};
Creates and initializes the master setup struct
Definition at line 391 of file ctrlproto_m.h.
#define MOTOR_PARAM_UPDATE 1
Definition at line 58 of file ctrlproto_m.h.
Referenced by sdo_motor_config_update(), and set_operation_mode().
#define POSITION_CTRL_UPDATE 4
Definition at line 61 of file ctrlproto_m.h.
Referenced by sdo_motor_config_update(), and set_operation_mode().
#define PP_MOTOR_UPDATE 6
Definition at line 63 of file ctrlproto_m.h.
Referenced by sdo_motor_config_update(), and set_operation_mode().
#define PV_MOTOR_UPDATE 5
Definition at line 62 of file ctrlproto_m.h.
Referenced by sdo_motor_config_update(), and set_operation_mode().
#define QEI_CALIBRATE_UPDATE 10
Definition at line 67 of file ctrlproto_m.h.
#define SOMANET_C22_CTRLPROTO_CSTRUCT ()
Value:
ec_pdo_entry_info_t ctrlproto_pdo_entries[] = {\
                {CAN_OD_CONTROL_WORD, 0x00, 16},\
                {CAN_OD_MODES, 0x00, 8},\
            {CAN_OD_TORQUE_TARGET, 0x00, 16},\
            {CAN_OD_POSITION_TARGET, 0x00, 32},\
            {CAN_OD_VELOCITY_TARGET, 0x00, 32},\
            {CAN_OD_STATUS_WORD, 0x00, 16},\
            {CAN_OD_MODES_DISPLAY, 0x00, 8},\
            {CAN_OD_POSITION_VALUE, 0x00, 32},\
            {CAN_OD_VELOCITY_VALUE, 0x00, 32},\
            {CAN_OD_TORQUE_VALUE, 0x00, 16},\
};\
\
ec_pdo_info_t ctrlproto_pdos[] = {\
    {0x1600, 5, ctrlproto_pdo_entries + 0},\
    {0x1a00, 5, ctrlproto_pdo_entries + 5},\
};\
\
ec_sync_info_t ctrlproto_syncs[] = {\
    {0, EC_DIR_OUTPUT, 0, NULL, EC_WD_DISABLE},\
    {1, EC_DIR_INPUT, 0, NULL, EC_WD_DISABLE},\
    {2, EC_DIR_OUTPUT, 1, ctrlproto_pdos + 0, EC_WD_DISABLE},\
    {3, EC_DIR_INPUT, 1, ctrlproto_pdos + 1, EC_WD_DISABLE},\
    {0xff}\
};\
This creates the defines for a SOMANET device running CTRLPROTO
Definition at line 86 of file ctrlproto_m.h.
#define SOMANET_C22_CTRLPROTO_DOMAIN_REGS_ENTRIES (ALIAS, POSITION, ARRAY_POSITION)
Value:
{ALIAS, POSITION, SOMANET_ID, CAN_OD_CONTROL_WORD,              0, &(slv_handles[ARRAY_POSITION].__ecat_slave_out[0])},\
{ALIAS, POSITION, SOMANET_ID, CAN_OD_MODES,                     0, &(slv_handles[ARRAY_POSITION].__ecat_slave_out[1])},\
{ALIAS, POSITION, SOMANET_ID, CAN_OD_TORQUE_TARGET,     0, &(slv_handles[ARRAY_POSITION].__ecat_slave_out[2])},\
{ALIAS, POSITION, SOMANET_ID, CAN_OD_POSITION_TARGET,   0, &(slv_handles[ARRAY_POSITION].__ecat_slave_out[3])},\
{ALIAS, POSITION, SOMANET_ID, CAN_OD_VELOCITY_TARGET,   0, &(slv_handles[ARRAY_POSITION].__ecat_slave_out[4])},\
{ALIAS, POSITION, SOMANET_ID, CAN_OD_STATUS_WORD,               0, &(slv_handles[ARRAY_POSITION].__ecat_slave_in[0])},\
{ALIAS, POSITION, SOMANET_ID, CAN_OD_MODES_DISPLAY,     0, &(slv_handles[ARRAY_POSITION].__ecat_slave_in[1])},\
{ALIAS, POSITION, SOMANET_ID, CAN_OD_POSITION_VALUE,    0, &(slv_handles[ARRAY_POSITION].__ecat_slave_in[2])},\
{ALIAS, POSITION, SOMANET_ID, CAN_OD_VELOCITY_VALUE,    0, &(slv_handles[ARRAY_POSITION].__ecat_slave_in[3])},\
{ALIAS, POSITION, SOMANET_ID, CAN_OD_TORQUE_VALUE,              0, &(slv_handles[ARRAY_POSITION].__ecat_slave_in[4])}
This creates a entry for the domain register for a SOMANET device running CTRLPROTO
Parameters
ALIAS The slaves alias
POSITION The position of the slave in the ethercat chain
ARRAY_POSITION The position of the entry of the slave inside the handles array
Definition at line 330 of file ctrlproto_m.h.
#define SOMANET_C22_CTRLPROTO_SLAVE_HANDLES_ENTRY (ALIAS, POSITION, CONFIG_NUMBER)
This creates a entry for the domain entry register for a SOMANET device running CTRLPROTO
Parameters
ALIAS The slaves alias
POSITION The position of the slave in the ethercat chain
Definition at line 121 of file ctrlproto_m.h.
#define SOMANET_ID 0x000022d2, 0x00000201
Definition at line 70 of file ctrlproto_m.h.
#define TORQUE_CTRL_UPDATE 8
Definition at line 65 of file ctrlproto_m.h.
Referenced by sdo_motor_config_update(), and set_operation_mode().
#define TQ_MOTOR_UPDATE 9
Definition at line 66 of file ctrlproto_m.h.
Referenced by sdo_motor_config_update(), and set_operation_mode().
#define VELOCITY_CTRL_UPDATE 2
Definition at line 59 of file ctrlproto_m.h.
Referenced by sdo_motor_config_update(), and set_operation_mode().
Function Documentation
void init_master (master_setup_variables_t * master_setup, ctrlproto_slv_handle * slv_handles, unsigned int total_no_of_slaves)
Initialises the Master and Slave communication
Parameters
master_setup A struct containing the variables for the master
slv_handles The handle struct for the slaves
total_no_of_slaves Number of connected slaves to the master
Definition at line 374 of file ctrlproto_m.c.
References master_setup_variables_t::domain, master_setup_variables_t::domain_pd, master_setup_variables_t::domain_regs, FREQUENCY, master_setup_variables_t::master, motor_config_request(), signal_handler(), ctrlproto_slv_handle::slave_alias, ctrlproto_slv_handle::slave_pos, ctrlproto_slv_handle::slave_productid, and ctrlproto_slv_handle::slave_vendorid.
Referenced by ecat_master().
void pdo_handle_ecat (master_setup_variables_t * master_setup, ctrlproto_slv_handle * slv_handles, unsigned int total_no_of_slaves)
This function handles the ethercat master communication, it wraps around the master loop around the functions standing below.
Parameters
master_setup A struct containing the variables for the master
slv_handles The handle struct for the slaves
total_no_of_slaves Number of connected slaves to the master
Definition at line 270 of file ctrlproto_m.c.
References ctrlproto_slv_handle::__ecat_slave_in, ctrlproto_slv_handle::__ecat_slave_out, master_setup_variables_t::domain, master_setup_variables_t::domain_pd, master_setup_variables_t::domain_state, master_setup_variables_t::master, master_setup_variables_t::master_state, ctrlproto_slv_handle::motorctrl_out, ctrlproto_slv_handle::motorctrl_status_in, master_setup_variables_t::op_flag, ctrlproto_slv_handle::operation_mode, ctrlproto_slv_handle::operation_mode_disp, ctrlproto_slv_handle::position_in, ctrlproto_slv_handle::position_setpoint, ctrlproto_slv_handle::speed_in, ctrlproto_slv_handle::speed_setpoint, ctrlproto_slv_handle::torque_in, and ctrlproto_slv_handle::torque_setpoint.
Referenced by ecat_master(), enable_operation(), init_node(), quick_stop(), quick_stop_position(), renable_ctrl_quick_stop(), renable_velocity_ctrl(), set_operation_mode(), and shutdown_operation().
void sdo_handle_ecat (master_setup_variables_t * master_setup, ctrlproto_slv_handle * slv_handles, int update_sequence, int slave_number)
This function updates the motor parameters via ethercat
Parameters
master_setup A struct containing the variables for the master
slv_handles The handle array for the slaves *
update_sequence Specify set of motor parameter to be configured
slave_number Specify the slave number to which the motor is connected
Definition at line 219 of file ctrlproto_m.c.
References master_setup_variables_t::domain, master_setup_variables_t::domain_state, master_setup_variables_t::master, master_setup_variables_t::master_state, ctrlproto_slv_handle::motor_config_param, master_setup_variables_t::op_flag, and sdo_motor_config_update().
Referenced by set_operation_mode().