ROS_ecat_master: src/profile_position.c File Reference
profile_position.c File Reference
Profile Generation for Position Implements position profile based on Linear Function with Parabolic Blends.
#include <profile.h>
Functions
void init_position_profile_limits (int gear_ratio, int max_acceleration, int max_velocity, profile_pos_param *profile_pos_params)
Initialise Position Profile Limits.
int init_position_profile (int target_position, int actual_position, int velocity, int acceleration, int deceleration, profile_pos_param *profile_pos_params)
Initialise Position Profile.
int position_profile_generate (int step, profile_pos_param *profile_pos_params)
Generate Position Profile.
int init_quick_stop_position_profile (int actual_velocity, int actual_position, int max_acceleration, pos_quick_stop_param *pos_param_s)
Initialise Quick Stop Position Profile.
int quick_stop_position_profile_generate (int steps, int actual_velocity, pos_quick_stop_param *pos_param_s)
Generate Quick Stop Position Profile.
Detailed Description
Profile Generation for Position Implements position profile based on Linear Function with Parabolic Blends.
Copyright (c) 2013, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file profile_position.c.
Function Documentation
int init_position_profile (int target_position, int actual_position, int velocity, int acceleration, int deceleration, profile_pos_param * profile_pos_params)
Initialise Position Profile.
Input
Parameters
target_position
actual_position
velocity for the position profile
acceleration for the position profile
deceleration for the position profile
Output
Returns
no. of steps for position profile : range [1 - steps]
Definition at line 54 of file profile_position.c.
References profile_pos_param::acc, profile_pos_param::acc_min, profile_pos_param::acc_too_low, profile_pos_param::ai, profile_pos_param::bi, profile_pos_param::ci, profile_pos_param::dec, profile_pos_param::di, profile_pos_param::direction, profile_pos_param::distance_acc, profile_pos_param::distance_cruise, profile_pos_param::distance_dec, profile_pos_param::distance_left, profile_pos_param::ei, profile_pos_param::fi, profile_pos_param::gear_ratio, profile_pos_param::gi, profile_pos_param::max_acceleration, profile_pos_param::max_velocity, profile_pos_param::qf, profile_pos_param::qfd, profile_pos_param::qi, profile_pos_param::qid, profile_pos_param::s_time, profile_pos_param::T, profile_pos_param::t_cruise, profile_pos_param::tb_acc, profile_pos_param::tb_dec, profile_pos_param::tf, profile_pos_param::total_distance, and profile_pos_param::vi.
Referenced by init_position_profile_params().
void init_position_profile_limits (int gear_ratio, int max_acceleration, int max_velocity, profile_pos_param * profile_pos_params)
Initialise Position Profile Limits.
Input
Parameters
gear_ratio
max_acceleration for the position profile
max_velocity for the position profile
Definition at line 47 of file profile_position.c.
References profile_pos_param::gear_ratio, profile_pos_param::max_acceleration, and profile_pos_param::max_velocity.
Referenced by ecat_master().
int init_quick_stop_position_profile (int actual_velocity, int actual_position, int max_acceleration, pos_quick_stop_param * pos_param_s)
Initialise Quick Stop Position Profile.
Input
Parameters
actual_velocity
actual_position
max_acceleration defines the deceleration for quick stop profile
Output
Returns
no. of steps for quick stop profile : range [1 - steps]
Definition at line 288 of file profile_position.c.
References pos_quick_stop_param::acc, pos_quick_stop_param::ci, pos_quick_stop_param::cur_pos_s, pos_quick_stop_param::qf, pos_quick_stop_param::qi, pos_quick_stop_param::samp, pos_quick_stop_param::t_int, and pos_quick_stop_param::tb.
int position_profile_generate (int step, profile_pos_param * profile_pos_params)
Generate Position Profile.
Input
Parameters
step current step of the profile
Output
Returns
corresponding target position at the step input
Definition at line 258 of file profile_position.c.
References profile_pos_param::ai, profile_pos_param::bi, profile_pos_param::ci, profile_pos_param::di, profile_pos_param::ei, profile_pos_param::fi, profile_pos_param::gi, profile_pos_param::q, profile_pos_param::s_time, profile_pos_param::tb_acc, profile_pos_param::tb_dec, profile_pos_param::tf, profile_pos_param::ts, and profile_pos_param::vi.
Referenced by ecat_master().
int quick_stop_position_profile_generate (int steps, int actual_velocity, pos_quick_stop_param * pos_param_s)
Generate Quick Stop Position Profile.
Input
Parameters
step current step of the profile
actual_velocity Output
Returns
corresponding target position at the step input
Definition at line 312 of file profile_position.c.
References pos_quick_stop_param::ci, pos_quick_stop_param::cur_pos_s, pos_quick_stop_param::q, pos_quick_stop_param::qf, pos_quick_stop_param::t_int, and pos_quick_stop_param::ts.