ROS_ecat_master: include/drive_function.h File Reference
drive_function.h File Reference
Motor Drive functions over Ethercat.
#include <drive_config.h>
#include <math.h>
#include "ctrlproto_m.h"
#include "profile.h"
Functions
int init_linear_profile_float (float target_value, float actual_value, float acceleration, float deceleration, float max_value)
Initialise Linear Profile.
float linear_profile_generate_float (int step)
Generate Linear Profile.
void init_node (int slave_number, master_setup_variables_t *master_setup, ctrlproto_slv_handle *slv_handles, int total_no_of_slaves)
Initialize node with basic motor configurations via bldc_motor_config.h.
int position_limit (float target_position, int slave_number, ctrlproto_slv_handle *slv_handles)
int set_operation_mode (int operation_mode, int slave_number, master_setup_variables_t *master_setup, ctrlproto_slv_handle *slv_handles, int total_no_of_slaves)
Sets operation mode via defines for modes of operation in drive_config.h.
int enable_operation (int slave_number, master_setup_variables_t *master_setup, ctrlproto_slv_handle *slv_handles, int total_no_of_slaves)
Enables the operation mode specified.
int shutdown_operation (int operation_mode, int slave_number, master_setup_variables_t *master_setup, ctrlproto_slv_handle *slv_handles, int total_no_of_slaves)
Shuts down the operation mode selected.
void set_position_degree (int target_position, int slave_number, ctrlproto_slv_handle *slv_handles)
Sets target position cyclically for Cyclic Synchronous Position(CSP) mode only.
void set_profile_position_degree (float target_position, int slave_number, ctrlproto_slv_handle *slv_handles)
Sets target position for Profile Position mode(PPM) only.
float get_position_actual_degree (int slave_number, ctrlproto_slv_handle *slv_handles)
Gets actual position.
int quick_stop_position (int slave_number, master_setup_variables_t *master_setup, ctrlproto_slv_handle *slv_handles, int total_no_of_slaves)
Quick Stop Position.
int target_position_reached (int slave_number, float target_position, float tolerance, ctrlproto_slv_handle *slv_handles)
Check target position reached for Profile position mode.
int init_position_profile_params (float target_position, float actual_position, int velocity, int acceleration, int deceleration, profile_pos_param *profile_pos_params)
Initialize Position Profile parameters.
void initialize_torque (int slave_number, ctrlproto_slv_handle *slv_handles)
Initialize Torque parameters for Profile Torque mode(PTM) & Cyclic Synchronous Torque(CST) mode.
int init_linear_profile_params (float target_torque, float actual_torque, float torque_slope, int slave_number, ctrlproto_slv_handle *slv_handles)
Initialize Linear Profile parameters for Profile torque mode.
void set_torque_mNm (float target_torque, int slave_number, ctrlproto_slv_handle *slv_handles)
Sets target torque for Profile Torque mode(PTM) & Cyclic Synchronous Torque(CST) mode.
float get_torque_actual_mNm (int slave_number, ctrlproto_slv_handle *slv_handles)
Gets actual torque.
int target_torque_reached (int slave_number, float target_torque, float tolerance, ctrlproto_slv_handle *slv_handles)
Check target torque reached for Profile torque Mode.
int quick_stop_torque (int slave_number, master_setup_variables_t *master_setup, ctrlproto_slv_handle *slv_handles, int total_no_of_slaves)
Quick Stop Torque.
void set_velocity_rpm (int target_velocity, int slave_number, ctrlproto_slv_handle *slv_handles)
Sets target velocity for Profile Velocity mode(PPM) & Cyclic Synchronous Velocity(CSV) mode.
int get_velocity_actual_rpm (int slave_number, ctrlproto_slv_handle *slv_handles)
Gets actual velocity.
int quick_stop_velocity (int slave_number, master_setup_variables_t *master_setup, ctrlproto_slv_handle *slv_handles, int total_no_of_slaves)
Quick Stop Velocity.
int target_velocity_reached (int slave_number, int target_velocity, int tolerance, ctrlproto_slv_handle *slv_handles)
Check target velocity reached for Profile velocity Mode.
int velocity_set_flag (int slave_number, ctrlproto_slv_handle *slv_handles)
Check velocity set for Profile velocity mode.
int position_set_flag (int slave_number, ctrlproto_slv_handle *slv_handles)
Check position set for Profile position mode.
int renable_ctrl_quick_stop (int operation_mode, int slave_number, master_setup_variables_t *master_setup, ctrlproto_slv_handle *slv_handles, int total_no_of_slaves)
Enable control after quick stop operation.
Detailed Description
Motor Drive functions over Ethercat.
Copyright (c) 2013, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file drive_function.h.
Function Documentation
int enable_operation (int slave_number, master_setup_variables_t * master_setup, ctrlproto_slv_handle * slv_handles, int total_no_of_slaves)
Enables the operation mode specified.
Parameters
slave_number Specify the slave number to which the motor is connected
master_setup A struct containing the variables for the master
slv_handles The handle struct for the slaves
total_no_of_slaves Number of connected slaves to the master
Definition at line 634 of file drive_function.c.
References check_op_enable(), master_setup_variables_t::op_flag, pdo_handle_ecat(), read_statusword(), set_controlword(), and SWITCH_ON.
Referenced by ecat_master().
float get_position_actual_degree (int slave_number, ctrlproto_slv_handle * slv_handles)
Gets actual position.
Parameters
slave_number Specify the slave number to which the motor is connected
slv_handles The handle struct for the slaves
Returns
actual_position from the slave number specified
Definition at line 111 of file drive_function.c.
Referenced by ecat_master(), quick_stop_position(), and target_position_reached().
float get_torque_actual_mNm (int slave_number, ctrlproto_slv_handle * slv_handles)
Gets actual torque.
Parameters
slave_number Specify the slave number to which the motor is connected
slv_handles The handle struct for the slaves
Returns
actual torque in mNm from the slave number specified
Definition at line 101 of file drive_function.c.
Referenced by target_torque_reached().
int get_velocity_actual_rpm (int slave_number, ctrlproto_slv_handle * slv_handles)
Gets actual velocity.
Parameters
slave_number Specify the slave number to which the motor is connected
slv_handles The handle struct for the slaves
Returns
actual_velocity in rpm from the slave number specified
Definition at line 106 of file drive_function.c.
References ctrlproto_slv_handle::speed_in.
Referenced by target_velocity_reached().
int init_linear_profile_float (float target_value, float actual_value, float acceleration, float deceleration, float max_value)
Initialise Linear Profile.
Input
Parameters
target_value
actual_value
acceleration for the Linear profile
deceleration for the Linear profile
max_value for the Linear profile
Output
Returns
no. of steps for linear profile : range [1 - steps-1]
Definition at line 165 of file profile_linear.c.
References PROFILE_LINEAR_PARAM::a_d, PROFILE_LINEAR_PARAM::acc, PROFILE_LINEAR_PARAM::dec, PROFILE_LINEAR_PARAM::oldst, profile_linear_params, PROFILE_LINEAR_PARAM::s_time, PROFILE_LINEAR_PARAM::t, PROFILE_LINEAR_PARAM::T, PROFILE_LINEAR_PARAM::u, and PROFILE_LINEAR_PARAM::v_d.
int init_linear_profile_params (float target_torque, float actual_torque, float torque_slope, int slave_number, ctrlproto_slv_handle * slv_handles)
Initialize Linear Profile parameters for Profile torque mode.
Parameters
target_torque Specify the target torque to follow (in mNm)
actual_torque Specify the actual torque (in mNm)
torque_slope Specify the torque slope (in mNm/s)
slave_number Specify the slave number to which the motor is connected
slv_handles The handle struct for the slaves
void init_node (int slave_number, master_setup_variables_t * master_setup, ctrlproto_slv_handle * slv_handles, int total_no_of_slaves)
Initialize node with basic motor configurations via bldc_motor_config.h.
Parameters
slave_number Specify the slave number to which the motor is connected
master_setup A struct containing the variables for the master
slv_handles The handle struct for the slaves
total_no_of_slaves Number of connected slaves to the master
Definition at line 260 of file drive_function.c.
References master_setup_variables_t::op_flag, pdo_handle_ecat(), and set_controlword().
Referenced by ecat_master().
int init_position_profile_params (float target_position, float actual_position, int velocity, int acceleration, int deceleration, profile_pos_param * profile_pos_params)
Initialize Position Profile parameters.
Parameters
target_position Specify the target position to follow (in degree)
actual_position Specify the actual position (in degree)
velocity Specify the velocity (in rpm)
acceleration Specify the acceleration (in rpm/s)
deceleration Specify the deceleration (in rpm/s)
Definition at line 197 of file drive_function.c.
References init_position_profile().
Referenced by ecat_master().
void initialize_torque (int slave_number, ctrlproto_slv_handle * slv_handles)
Initialize Torque parameters for Profile Torque mode(PTM) & Cyclic Synchronous Torque(CST) mode.
Parameters
slave_number Specify the slave number to which the motor is connected
slv_handles The handle struct for the slaves
Definition at line 84 of file drive_function.c.
References ctrlproto_slv_handle::factor_torq, ctrlproto_slv_handle::motor_config_param, nominal_current_s::nominal_current, and motor_config::s_nominal_current.
float linear_profile_generate_float (int step)
Generate Linear Profile.
Input
Parameters
step current step of the profile
Output
Returns
corresponding target value at the step input
Definition at line 264 of file profile_linear.c.
References PROFILE_LINEAR_PARAM::a_d, profile_linear_params, PROFILE_LINEAR_PARAM::s_time, and PROFILE_LINEAR_PARAM::u.
int position_limit (float target_position, int slave_number, ctrlproto_slv_handle * slv_handles)
Definition at line 118 of file drive_function.c.
References ctrlproto_slv_handle::motor_config_param, motor_config::s_software_position_max, and software_position_max_s::software_position_max.
Referenced by set_profile_position_degree().
int position_set_flag (int slave_number, ctrlproto_slv_handle * slv_handles)
Check position set for Profile position mode.
Parameters
slave_number Specify the slave number to which the motor is connected
slv_handles The handle struct for the slaves
Definition at line 169 of file drive_function.c.
References check_target_reached(), and read_statusword().
int quick_stop_position (int slave_number, master_setup_variables_t * master_setup, ctrlproto_slv_handle * slv_handles, int total_no_of_slaves)
Quick Stop Position.
Parameters
slave_number Specify the slave number to which the motor is connected
master_setup A struct containing the variables for the master
slv_handles The handle struct for the slaves
total_no_of_slaves Number of connected slaves to the master
Definition at line 661 of file drive_function.c.
References check_quick_stop_active(), ENABLE_OPERATION_CONTROL, ENABLE_VOLTAGE_CONTROL, get_position_actual_degree(), master_setup_variables_t::op_flag, pdo_handle_ecat(), QUICK_STOP_CONTROL, read_statusword(), set_controlword(), set_position_degree(), and SWITCH_ON_CONTROL.
Referenced by ecat_master().
int quick_stop_torque (int slave_number, master_setup_variables_t * master_setup, ctrlproto_slv_handle * slv_handles, int total_no_of_slaves)
Quick Stop Torque.
Parameters
slave_number Specify the slave number to which the motor is connected
master_setup A struct containing the variables for the master
slv_handles The handle struct for the slaves
total_no_of_slaves Number of connected slaves to the master
Definition at line 828 of file drive_function.c.
References quick_stop().
int quick_stop_velocity (int slave_number, master_setup_variables_t * master_setup, ctrlproto_slv_handle * slv_handles, int total_no_of_slaves)
Quick Stop Velocity.
Parameters
slave_number Specify the slave number to which the motor is connected
master_setup A struct containing the variables for the master
slv_handles The handle struct for the slaves
total_no_of_slaves Number of connected slaves to the master
Definition at line 833 of file drive_function.c.
References quick_stop().
int renable_ctrl_quick_stop (int operation_mode, int slave_number, master_setup_variables_t * master_setup, ctrlproto_slv_handle * slv_handles, int total_no_of_slaves)
Enable control after quick stop operation.
Parameters
operation_mode Specify the operation mode selected for the slave
slave_number Specify the slave number to which the motor is connected
master_setup A struct containing the variables for the master
slv_handles The handle struct for the slaves
total_no_of_slaves Number of connected slaves to the master
Definition at line 707 of file drive_function.c.
References master_setup_variables_t::op_flag, ctrlproto_slv_handle::operation_mode, pdo_handle_ecat(), ctrlproto_slv_handle::position_in, ctrlproto_slv_handle::position_setpoint, QUICK_STOP_CONTROL, set_controlword(), ctrlproto_slv_handle::speed_in, ctrlproto_slv_handle::speed_setpoint, ctrlproto_slv_handle::torque_in, and ctrlproto_slv_handle::torque_setpoint.
Referenced by ecat_master().
int set_operation_mode (int operation_mode, int slave_number, master_setup_variables_t * master_setup, ctrlproto_slv_handle * slv_handles, int total_no_of_slaves)
Sets operation mode via defines for modes of operation in drive_config.h.
Parameters
operation_mode Specify the operation mode for the slave
slave_number Specify the slave number to which the motor is connected
master_setup A struct containing the variables for the master
slv_handles The handle struct for the slaves
total_no_of_slaves Number of connected slaves to the master
Definition at line 276 of file drive_function.c.
References check_ready(), check_switch_enable(), check_switch_on(), CSP, CST, CST_MOTOR_UPDATE, CSV, CSV_MOTOR_UPDATE, ctrlproto_slv_handle::factor_torq, ctrlproto_slv_handle::motor_config_param, MOTOR_PARAM_UPDATE, master_setup_variables_t::op_flag, ctrlproto_slv_handle::operation_mode, pdo_handle_ecat(), POSITION_CTRL_UPDATE, PP, PP_MOTOR_UPDATE, PV, PV_MOTOR_UPDATE, read_statusword(), motor_config::s_torque_slope, sdo_handle_ecat(), set_controlword(), SWITCH_ON_CONTROL, TORQUE_CTRL_UPDATE, torque_slope_s::torque_slope, TQ, TQ_MOTOR_UPDATE, motor_config::update_flag, and VELOCITY_CTRL_UPDATE.
Referenced by ecat_master().
void set_position_degree (int target_position, int slave_number, ctrlproto_slv_handle * slv_handles)
Sets target position cyclically for Cyclic Synchronous Position(CSP) mode only.
Parameters
target_position Specify the target position to follow (in degree)
slave_number Specify the slave number to which the motor is connected
slv_handles The handle struct for the slaves
Definition at line 141 of file drive_function.c.
References ctrlproto_slv_handle::motor_config_param, ctrlproto_slv_handle::position_setpoint, motor_config::s_software_position_max, motor_config::s_software_position_min, software_position_max_s::software_position_max, and software_position_min_s::software_position_min.
Referenced by ecat_master(), and quick_stop_position().
void set_profile_position_degree (float target_position, int slave_number, ctrlproto_slv_handle * slv_handles)
Sets target position for Profile Position mode(PPM) only.
Parameters
target_position Specify the target position to follow (in degree)
slave_number Specify the slave number to which the motor is connected
slv_handles The handle struct for the slaves
Definition at line 163 of file drive_function.c.
References position_limit(), and ctrlproto_slv_handle::position_setpoint.
void set_torque_mNm (float target_torque, int slave_number, ctrlproto_slv_handle * slv_handles)
Sets target torque for Profile Torque mode(PTM) & Cyclic Synchronous Torque(CST) mode.
Parameters
target_torque Specify the target torque to follow (in mNm)
slave_number Specify the slave number to which the motor is connected
slv_handles The handle struct for the slaves
Definition at line 95 of file drive_function.c.
References ctrlproto_slv_handle::factor_torq, and ctrlproto_slv_handle::torque_setpoint.
void set_velocity_rpm (int target_velocity, int slave_number, ctrlproto_slv_handle * slv_handles)
Sets target velocity for Profile Velocity mode(PPM) & Cyclic Synchronous Velocity(CSV) mode.
Parameters
target_velocity Specify the target velocity to follow (in rpm)
slave_number Specify the slave number to which the motor is connected
slv_handles The handle struct for the slaves
Definition at line 79 of file drive_function.c.
References ctrlproto_slv_handle::speed_setpoint.
int shutdown_operation (int operation_mode, int slave_number, master_setup_variables_t * master_setup, ctrlproto_slv_handle * slv_handles, int total_no_of_slaves)
Shuts down the operation mode selected.
Parameters
operation_mode Specify the operation mode selected for the slave
slave_number Specify the slave number to which the motor is connected
master_setup A struct containing the variables for the master
slv_handles The handle struct for the slaves
total_no_of_slaves Number of connected slaves to the master
Definition at line 757 of file drive_function.c.
References check_shutdown_active(), master_setup_variables_t::op_flag, ctrlproto_slv_handle::operation_mode, pdo_handle_ecat(), read_statusword(), set_controlword(), and SHUTDOWN.
Referenced by ecat_master().
int target_position_reached (int slave_number, float target_position, float tolerance, ctrlproto_slv_handle * slv_handles)
Check target position reached for Profile position mode.
Parameters
slave_number Specify the slave number to which the motor is connected
target_position Specify the target position set (in degree)
tolerance Specify the tolerance for target position
slv_handles The handle struct for the slaves
Returns
1 if target position reached else 0
Definition at line 212 of file drive_function.c.
References check_target_reached(), get_position_actual_degree(), and read_statusword().
int target_torque_reached (int slave_number, float target_torque, float tolerance, ctrlproto_slv_handle * slv_handles)
Check target torque reached for Profile torque Mode.
Parameters
slave_number Specify the slave number to which the motor is connected
target_torque Specify the target torque set (in nNm)
tolerance Specify the tolerance for target torque (in mNm)
slv_handles The handle struct for the slaves
Returns
1 if target torque reached else 0
Definition at line 244 of file drive_function.c.
References check_target_reached(), get_torque_actual_mNm(), and read_statusword().
int target_velocity_reached (int slave_number, int target_velocity, int tolerance, ctrlproto_slv_handle * slv_handles)
Check target velocity reached for Profile velocity Mode.
Parameters
slave_number Specify the slave number to which the motor is connected
target_velocity Specify the target velocity set (in rpm)
tolerance Specify the tolerance for target velocity
slv_handles The handle struct for the slaves
Definition at line 228 of file drive_function.c.
References check_target_reached(), get_velocity_actual_rpm(), and read_statusword().
int velocity_set_flag (int slave_number, ctrlproto_slv_handle * slv_handles)
Check velocity set for Profile velocity mode.
Parameters
slave_number Specify the slave number to which the motor is connected
slv_handles The handle struct for the slaves
Definition at line 178 of file drive_function.c.
References check_target_reached(), and read_statusword().