ROS_ecat_master: src/ctrlproto_m.c File Reference
ctrlproto_m.c File Reference
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <sys/resource.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdarg.h>
#include <ctrlproto_m.h>
#include <canod.h>
#include "ecrt.h"
Macros
#define FREQUENCY 1000
#define PRIORITY 1
Functions
void check_domain1_state (master_setup_variables_t *master_setup)
void check_master_state (master_setup_variables_t *master_setup)
int read_sdo (ec_sdo_request_t *req)
int write_sdo (ec_sdo_request_t *req, unsigned data)
motor_config sdo_motor_config_update (motor_config motor_config_param, ec_sdo_request_t *request[], int update_sequence)
void sdo_handle_ecat (master_setup_variables_t *master_setup, ctrlproto_slv_handle *slv_handles, int update_sequence, int slave_number)
void pdo_handle_ecat (master_setup_variables_t *master_setup, ctrlproto_slv_handle *slv_handles, unsigned int total_no_of_slaves)
void signal_handler (int signum)
void motor_config_request (ec_slave_config_t *slave_config, ec_sdo_request_t *request[])
void init_master (master_setup_variables_t *master_setup, ctrlproto_slv_handle *slv_handles, unsigned int total_no_of_slaves)
ec_sdo_request_t * _config_sdo_request (ec_slave_config_t *slave_config, ec_sdo_request_t *request, int index, int sub_index, int bytes)
int _motor_config_update (ec_sdo_request_t *request, int update, int value, int sequence)
Detailed Description
Copyright (c) 2014, Synapticon GmbH All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file ctrlproto_m.c.
Macro Definition Documentation
#define FREQUENCY 1000
Definition at line 89 of file ctrlproto_m.c.
Referenced by init_master().
#define PRIORITY 1
Definition at line 90 of file ctrlproto_m.c.
Function Documentation
ec_sdo_request_t* _config_sdo_request (ec_slave_config_t * slave_config, ec_sdo_request_t * request, int index, int sub_index, int bytes)
Definition at line 454 of file ctrlproto_m.c.
Referenced by motor_config_request().
int _motor_config_update (ec_sdo_request_t * request, int update, int value, int sequence)
Definition at line 502 of file ctrlproto_m.c.
References read_sdo(), and write_sdo().
Referenced by sdo_motor_config_update().
void check_domain1_state (master_setup_variables_t * master_setup)
Definition at line 111 of file ctrlproto_m.c.
References master_setup_variables_t::domain, and master_setup_variables_t::domain_state.
void check_master_state (master_setup_variables_t * master_setup)
Definition at line 127 of file ctrlproto_m.c.
References master_setup_variables_t::master, and master_setup_variables_t::master_state.
void init_master (master_setup_variables_t * master_setup, ctrlproto_slv_handle * slv_handles, unsigned int total_no_of_slaves)
Initialises the Master and Slave communication
Parameters
master_setup A struct containing the variables for the master
slv_handles The handle struct for the slaves
total_no_of_slaves Number of connected slaves to the master
Definition at line 374 of file ctrlproto_m.c.
References master_setup_variables_t::domain, master_setup_variables_t::domain_pd, master_setup_variables_t::domain_regs, FREQUENCY, master_setup_variables_t::master, motor_config_request(), signal_handler(), ctrlproto_slv_handle::slave_alias, ctrlproto_slv_handle::slave_pos, ctrlproto_slv_handle::slave_productid, and ctrlproto_slv_handle::slave_vendorid.
Referenced by ecat_master().
void motor_config_request (ec_slave_config_t * slave_config, ec_sdo_request_t * request[])
Definition at line 464 of file ctrlproto_m.c.
References _config_sdo_request(), CIA402_CURRENT_GAIN, CIA402_GEAR_RATIO, CIA402_MAX_ACCELERATION, CIA402_MAX_PROFILE_VELOCITY, CIA402_MAX_TORQUE, CIA402_MOTOR_SPECIFIC, CIA402_POLARITY, CIA402_POSITION_ENC_RESOLUTION, CIA402_POSITION_GAIN, CIA402_PROFILE_ACCELERATION, CIA402_PROFILE_DECELERATION, CIA402_PROFILE_VELOCITY, CIA402_QUICK_STOP_DECELERATION, CIA402_SENSOR_SELECTION_CODE, CIA402_SOFTWARE_POSITION_LIMIT, CIA402_TORQUE_SLOPE, and CIA402_VELOCITY_GAIN.
Referenced by init_master().
void pdo_handle_ecat (master_setup_variables_t * master_setup, ctrlproto_slv_handle * slv_handles, unsigned int total_no_of_slaves)
This function handles the ethercat master communication, it wraps around the master loop around the functions standing below.
Parameters
master_setup A struct containing the variables for the master
slv_handles The handle struct for the slaves
total_no_of_slaves Number of connected slaves to the master
Definition at line 270 of file ctrlproto_m.c.
References ctrlproto_slv_handle::__ecat_slave_in, ctrlproto_slv_handle::__ecat_slave_out, master_setup_variables_t::domain, master_setup_variables_t::domain_pd, master_setup_variables_t::domain_state, master_setup_variables_t::master, master_setup_variables_t::master_state, ctrlproto_slv_handle::motorctrl_out, ctrlproto_slv_handle::motorctrl_status_in, master_setup_variables_t::op_flag, ctrlproto_slv_handle::operation_mode, ctrlproto_slv_handle::operation_mode_disp, ctrlproto_slv_handle::position_in, ctrlproto_slv_handle::position_setpoint, ctrlproto_slv_handle::speed_in, ctrlproto_slv_handle::speed_setpoint, ctrlproto_slv_handle::torque_in, and ctrlproto_slv_handle::torque_setpoint.
Referenced by ecat_master(), enable_operation(), init_node(), quick_stop(), quick_stop_position(), renable_ctrl_quick_stop(), renable_velocity_ctrl(), set_operation_mode(), and shutdown_operation().
int read_sdo (ec_sdo_request_t * req)
Definition at line 164 of file ctrlproto_m.c.
Referenced by _motor_config_update().
void sdo_handle_ecat (master_setup_variables_t * master_setup, ctrlproto_slv_handle * slv_handles, int update_sequence, int slave_number)
This function updates the motor parameters via ethercat
Parameters
master_setup A struct containing the variables for the master
slv_handles The handle array for the slaves *
update_sequence Specify set of motor parameter to be configured
slave_number Specify the slave number to which the motor is connected
Definition at line 219 of file ctrlproto_m.c.
References master_setup_variables_t::domain, master_setup_variables_t::domain_state, master_setup_variables_t::master, master_setup_variables_t::master_state, ctrlproto_slv_handle::motor_config_param, master_setup_variables_t::op_flag, and sdo_motor_config_update().
Referenced by set_operation_mode().
motor_config sdo_motor_config_update (motor_config motor_config_param, ec_sdo_request_t * request[], int update_sequence)
Definition at line 523 of file ctrlproto_m.c.
References _motor_config_update(), CST_MOTOR_UPDATE, CSV_MOTOR_UPDATE, velocity_d_gain_s::d_gain, gear_ratio_s::gear_ratio, velocity_i_gain_s::i_gain, max_acceleration_s::max_acceleration, max_profile_velocity_s::max_profile_velocity, max_torque_s::max_torque, MOTOR_PARAM_UPDATE, motor_torque_constant_s::motor_torque_constant, nominal_current_s::nominal_current, nominal_motor_speed_s::nominal_motor_speed, velocity_p_gain_s::p_gain, polarity_s::polarity, pole_pair_s::pole_pair, POSITION_CTRL_UPDATE, position_encoder_resolution_s::position_encoder_resolution, PP_MOTOR_UPDATE, profile_acceleration_s::profile_acceleration, profile_deceleration_s::profile_deceleration, profile_velocity_s::profile_velocity, PV_MOTOR_UPDATE, quick_stop_deceleration_s::quick_stop_deceleration, motor_config::s_gear_ratio, motor_config::s_max_acceleration, motor_config::s_max_profile_velocity, motor_config::s_max_torque, motor_config::s_motor_torque_constant, motor_config::s_nominal_current, motor_config::s_nominal_motor_speed, motor_config::s_polarity, motor_config::s_pole_pair, motor_config::s_position_d_gain, motor_config::s_position_encoder_resolution, motor_config::s_position_i_gain, motor_config::s_position_p_gain, motor_config::s_profile_acceleration, motor_config::s_profile_deceleration, motor_config::s_profile_velocity, motor_config::s_quick_stop_deceleration, motor_config::s_sensor_selection_code, motor_config::s_software_position_max, motor_config::s_software_position_min, motor_config::s_torque_d_gain, motor_config::s_torque_i_gain, motor_config::s_torque_p_gain, motor_config::s_torque_slope, motor_config::s_velocity_d_gain, motor_config::s_velocity_i_gain, motor_config::s_velocity_p_gain, sensor_selection_code_s::sensor_selection_code, software_position_max_s::software_position_max, software_position_min_s::software_position_min, TORQUE_CTRL_UPDATE, torque_slope_s::torque_slope, TQ_MOTOR_UPDATE, motor_config::update_flag, pole_pair_s::update_state, gear_ratio_s::update_state, nominal_motor_speed_s::update_state, nominal_current_s::update_state, max_acceleration_s::update_state, position_encoder_resolution_s::update_state, polarity_s::update_state, sensor_selection_code_s::update_state, velocity_p_gain_s::update_state, velocity_i_gain_s::update_state, velocity_d_gain_s::update_state, software_position_min_s::update_state, software_position_max_s::update_state, max_profile_velocity_s::update_state, profile_acceleration_s::update_state, profile_deceleration_s::update_state, quick_stop_deceleration_s::update_state, profile_velocity_s::update_state, max_torque_s::update_state, torque_slope_s::update_state, motor_torque_constant_s::update_state, and VELOCITY_CTRL_UPDATE.
Referenced by sdo_handle_ecat().
void signal_handler (int signum)
Definition at line 349 of file ctrlproto_m.c.
Referenced by init_master().
int write_sdo (ec_sdo_request_t * req, unsigned data)
Definition at line 188 of file ctrlproto_m.c.
Referenced by _motor_config_update().